Update CI
Update CI
Fix Unstable PKI Unit Tests
Add Strong Name

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,40 +5,11 @@ on:
     branches:
     - master
     - github-workflow
-permissions:
-      contents: read
-      actions: read
-      checks: write
 jobs:
-  build:
-    strategy:
-      matrix:
-        os:
-        - 'ubuntu-latest'
-        - 'windows-latest'
-
-    runs-on: ${{ matrix.os }}
+  Build:
+    runs-on: ubuntu-latest
 
     steps:
-    - name: Prep CI
-      id: prep_ci
-      shell: pwsh
-      env:
-        MATRIX_OS: ${{ matrix.os }}
-      run: |
-        Install-Module GitHubActions -Force
-        Install-Module AWSPowerShell.NetCore -Force
-
-        Import-Module GitHubActions
-
-        $matrix_os = $env:MATRIX_OS
-        if ([string]::IsNullOrWhiteSpace($matrix_os)) { $matrix_os = 'unknown' }
-        $os_label = $matrix_os.Split('-')[0]
-
-        Write-ActionInfo "Resolved `$env:OS_LABEL as [$os_label]"
-        Set-ActionVariable -Name OS_LABEL -Value $os_label
-        Set-ActionOutput   -Name os_label -Value $os_label
-
     - name: Checkout latest
       uses: actions/checkout@v2
 
@@ -49,118 +20,51 @@ jobs:
 
     - name: Install dependencies
       run: dotnet restore
+    
+    - name: Signing Key
+      id: write_sign_key_file
+      uses: timheuer/base64-to-file@v1
+      with:
+        fileName: 'Key.snk'
+        encodedString: ${{ secrets.SIGNING_KEY }} 
 
     - name: Build
       run: dotnet build --configuration Release --no-restore
-      #run: dotnet build --configuration Release
-   
-    - name: Prepare for Tests
-      id: prep_tests
       env:
-        TEST_BUCKET_NAME: ${{ secrets.TEST_BUCKET_NAME }}
-        TEST_HOSTED_ZONE_ID: ${{ secrets.TEST_HOSTED_ZONE_ID }}
-        TEST_AWS_ACCESS_KEY: ${{ secrets.TEST_AWS_ACCESS_KEY }}
-        TEST_AWS_SECRET_KEY: ${{ secrets.TEST_AWS_SECRET_KEY }}
-      shell: pwsh
-      run: |
-        $configRoot      = "./test/ACMESharp.IntegrationTests/config"
-        $configOutRoot   = [System.IO.Path]::Combine($configRoot, "_IGNORE")
-        $configTemplates = [System.IO.Path]::Combine($configRoot, "template-*")
-        $configValues    = [System.Environment]::GetEnvironmentVariables()
+        SignAssembly: true
+        AssemblyOriginatorKeyFile: ${{ steps.write_sign_key_file.outputs.filePath }}
 
-        if (-not (Test-Path -PathType Container $configOutRoot)) {
-            mkdir $configOutRoot
-        }
-
-        ## For each config template, do a @@ENV_VAR@@ substitution
-        ## as we write out the realized template to the config dir
-        foreach ($f in (dir $configTemplates)) {
-            $fOut = $f.FullName -replace '[\\/]template-','/_IGNORE/'
-            $fBody = [System.IO.File]::ReadAllText($f.FullName)
-            foreach ($k in $configValues.Keys) {
-                $fBody = $fBody -replace "@@$k@@",$configValues[$k]
-            }
-            [System.IO.File]::WriteAllText("$($fOut)", $fBody)
-        }
-
-        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
-        #if ($isLinux) {
-        #    & sudo pwsh -C "Install-Module AWSPowerShell.NetCore -Force"
-        #}
-        #else {
-        #    Install-Module AWSPowerShell.NetCore -Force
-        #}
-
-        Import-Module AWSPowerShell.NetCore -Force
-        Set-AWSCredential -StoreAs acmesharp-tests -AccessKey $env:TEST_AWS_ACCESS_KEY -SecretKey $env:TEST_AWS_SECRET_KEY
-
-        #dotnet msbuild /t:clean
-        #dotnet msbuild /t:restore
-        #dotnet msbuild /t:build
-        #dotnet msbuild /t:publish
-
-        #dotnet pack src/ACMESharp
-        #dotnet pack src/ACMESharp.DotNetCore
-        #dotnet pack src/ACMESharp.MockServer
-        #dotnet pack src/PKISharp.SimplePKI
-
-    ## These are each separated out so we can better
-    ## distinguish, isolate and navigate the results
-    ## and each will always execute regardless of the
-    ## result of any preceding test as long as
-    - name: Test (ACMESharp)
-      if: ${{ !cancelled() }}
-      run: dotnet test --verbosity normal --logger "trx;LogFileName=ACMESharp-${{ matrix.os }}.trx" --results-directory coverage ./test/ACMESharp.UnitTests
-    - name: Test (SimplePKI)
-      if: ${{ !cancelled()  }}
-      run: dotnet test --verbosity normal --logger "trx;LogFileName=SimplePKI-${{ matrix.os }}.trx" --results-directory coverage ./test/PKISharp.SimplePKI.UnitTests
-    - name: Test (MockServer)
-      if: ${{ !cancelled()  }}
-      run: dotnet test --verbosity normal --logger "trx;LogFileName=MockServer-${{ matrix.os }}.trx" --results-directory coverage ./test/ACMESharp.MockServer.UnitTests
-    - uses: actions/upload-artifact@v4  # upload test results
-      if: success() || failure()        # run this step even if previous step failed
+    - name: Upload Artificats
+      uses: actions/upload-artifact@v4
       with:
-        name: "test-results-${{ matrix.os }}" 
-        path: coverage/*.trx
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
-      with:
-        artifact: "test-results-${{ matrix.os }}"   # Name of the artifact to upload
-        name: Test Results            # Name of the check run which will be created
-        path: "*.trx"    # Path to test results
-        reporter: dotnet-trx       # Format of test results
-
-    #- name: Test - Unit Tests
-    #  id: unitTests
-    #  if: ${{ !cancelled() }}
-    #  shell: pwsh
-    #  run: |
-    #    dotnet test --no-restore --verbosity normal --results-directory ./_IGNORE --logger "trx;LogFileName=_gh-tests.trx" ./test/ACMESharp.UnitTests
-    #    #./tools/test-report/trx2md.ps1 -trxFile ./_IGNORE/_gh-tests.trx -Verbose
-
-    #- name: Test - SimplePKI Unit Tests
-    #  id: simplePkiUnitTests
-    #  if: ${{ !cancelled() }}
-    #  shell: pwsh
-    #  run: dotnet test --no-restore --verbosity normal ./test/PKISharp.SimplePKI.UnitTests
-
-    #- name: Test - MockServer Unit Tests
-    #  id: mockServerUnitTests
-    #  if: ${{ !cancelled() }}
-    #  shell: pwsh
-    #  run: dotnet test --no-restore --verbosity normal ./test/ACMESharp.MockServer.UnitTests
-
-    #- name: Test - Integration Tests
-    #  id: integrationTests
-    #  if: ${{ !cancelled() && steps.unitTests.outcome == 'success' && steps.mockServerUnitTests.outcome == 'success' && steps.simplePkiUnitTests.outcome == 'success' }}
-    #  continue-on-error: true
-    #  shell: pwsh
-    #  run: |
-    #    ipmo GitHubActions
-    #    Write-ActionInfo "Results of preceding Tests:"
-    #    Write-ActionInfo "  * unitTests..............: ${{ steps.unitTests.outcome }}"
-    #    Write-ActionInfo "  * mockServerUnitTests....: ${{ steps.mockServerUnitTests.outcome }}"
-    #    Write-ActionInfo "  * simplePkiUnitTests.....: ${{ steps.simplePkiUnitTests.outcome }}"
-
-    #    dotnet test --no-restore --verbosity normal ./test/ACMESharp.IntegrationTests
+        name: TestBinaries
+        path: test/**/bin/*
+  
+  UnitTest:
+    name: Run Unit Tests
+    needs: Build
+    strategy:
+      matrix:
+        os:
+        - 'ubuntu-latest'
+        - 'windows-latest'
+        test:
+        - 'ACMESharp.UnitTests'
+        - 'PKISharp.SimplePKI.UnitTests'
+        - 'ACMESharp.MockServer.UnitTests'
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Checkout latest
+        uses: actions/checkout@v2
+      - uses: actions/download-artifact@v4
+        with:
+          name: TestBinaries
+      - name: Test (${{ matrix.test }})
+        if: ${{ !cancelled() }}
+        run: dotnet test --verbosity normal --logger "trx;LogFileName=${{ matrix.test }}-${{ matrix.os }}.trx" --results-directory coverage ${{ matrix.test }}/bin/Release/net8.0/${{ matrix.test }}.dll
+      - uses: dorny/test-reporter@v1
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: Test Result (${{ matrix.test }}-${{ matrix.os }})" 
+          path: coverage/*.trx
+          reporter: dotnet-trx
